// OpenRouter 常用词兜底字典（全小写键）
// 兜底规则：整段文本的每个词都必须在此表（或 OR_DROP 中），否则整体跳过，避免误翻专有名词
// 冠词等无实义词在 OR_DROP 中直接省略
const OR_COMMON = {
  and: "和", or: "或", but: "但", not: "不", of: "的", to: "到", for: "用于", with: "与",
  by: "由", from: "从", at: "在", in: "在", on: "在", as: "作为", is: "是", are: "是",
  was: "是", were: "是", be: "是", has: "有", have: "有", had: "有", do: "执行", does: "执行",
  did: "执行", will: "将", would: "将", can: "可以", could: "可以", should: "应该",
  may: "可能", might: "可能", must: "必须", this: "这个", that: "那个", these: "这些",
  those: "那些", it: "它", its: "它的", you: "您", your: "您的", we: "我们", our: "我们的",
  they: "他们", their: "他们的", he: "他", she: "她", his: "他的", her: "她的", me: "我",
  my: "我的", all: "所有", any: "任何", some: "一些", each: "每个", every: "每个",
  other: "其他", another: "另一个", more: "更多", less: "更少", most: "最多", least: "最少",
  few: "少数", many: "许多", much: "许多", very: "非常", too: "也", only: "仅", just: "仅",
  also: "也", even: "甚至", still: "仍然", already: "已经", always: "总是", never: "从不",
  often: "经常", usually: "通常", sometimes: "有时", new: "新", old: "旧", free: "免费",
  paid: "付费", public: "公开", private: "私有", open: "开放", closed: "关闭", active: "启用",
  inactive: "停用", enabled: "启用", disabled: "禁用", default: "默认", custom: "自定义",
  advanced: "高级", basic: "基础", simple: "简单", fast: "快速", slow: "缓慢", high: "高",
  low: "低", best: "最佳", better: "更好", good: "良好", great: "很棒", top: "热门",
  popular: "热门", featured: "精选", recommended: "推荐", trending: "热门", latest: "最新",
  recent: "最近", upcoming: "即将推出", daily: "每日", weekly: "每周", monthly: "每月",
  yearly: "每年", total: "总计", average: "平均", overall: "综合", general: "通用",
  main: "主要", primary: "主要", secondary: "次要", optional: "可选", required: "必填",
  first: "首个", last: "最后", next: "下一个", previous: "上一个", current: "当前",
  final: "最终", early: "早期", available: "可用", unavailable: "不可用", limited: "有限",
  unlimited: "无限", valid: "有效", invalid: "无效", success: "成功", error: "错误",
  warning: "警告", info: "信息", normal: "正常", manual: "手动", automatic: "自动",
  full: "完整", partial: "部分", empty: "空", single: "单个", multiple: "多个",
  maximum: "最大值", minimum: "最小值", max: "最大", min: "最小", add: "添加", edit: "编辑",
  delete: "删除", remove: "移除", create: "创建", save: "保存", cancel: "取消",
  confirm: "确认", submit: "提交", apply: "应用", update: "更新", change: "更改",
  modify: "修改", copy: "复制", paste: "粘贴", share: "分享", export: "导出", import: "导入",
  download: "下载", upload: "上传", view: "查看", show: "显示", hide: "隐藏", open: "打开",
  close: "关闭", start: "开始", stop: "停止", begin: "开始", end: "结束", finish: "完成",
  complete: "完成", continue: "继续", retry: "重试", refresh: "刷新", reset: "重置",
  clear: "清除", search: "搜索", find: "查找", select: "选择", choose: "选择", filter: "筛选",
  sort: "排序", manage: "管理", control: "控制", enable: "启用", disable: "禁用",
  allow: "允许", block: "阻止", accept: "接受", reject: "拒绝", approve: "批准",
  request: "请求", send: "发送", receive: "接收", get: "获取", put: "放置", post: "发布",
  read: "读取", write: "写入", set: "设置", run: "运行", test: "测试", debug: "调试",
  build: "构建", deploy: "部署", install: "安装", uninstall: "卸载", login: "登录",
  signin: "登录", signout: "退出", logout: "退出", register: "注册", verify: "验证",
  email: "邮箱", password: "密码", username: "用户名", name: "名称", address: "地址",
  phone: "电话", number: "号码", code: "代码", key: "密钥", token: "令牌", model: "模型",
  provider: "提供商", endpoint: "端点", response: "响应", usage: "用量", spend: "支出",
  balance: "余额", credit: "积分", billing: "账单", payment: "支付", invoice: "发票",
  receipt: "收据", transaction: "交易", history: "历史", activity: "活动", log: "日志",
  logs: "日志", settings: "设置", profile: "资料", account: "账户", workspace: "工作区",
  organization: "组织", team: "团队", member: "成员", admin: "管理员", owner: "所有者",
  role: "角色", permission: "权限", policy: "策略", rule: "规则", budget: "预算",
  limit: "限额", quota: "配额", status: "状态", type: "类型", category: "分类",
  feature: "功能", version: "版本", release: "发布", notification: "通知", alert: "提醒",
  message: "消息", chat: "对话", session: "会话", language: "语言", region: "地区",
  country: "国家", city: "城市", timezone: "时区", time: "时间", date: "日期", month: "月份",
  year: "年份", day: "天", week: "周", hour: "小时", minute: "分钟", second: "秒",
  format: "格式", size: "大小", length: "长度", width: "宽度", height: "高度", color: "颜色",
  theme: "主题", appearance: "外观", plan: "套餐", subscription: "订阅", trial: "试用",
  price: "价格", cost: "成本", fee: "费用", rate: "费率", amount: "金额", quantity: "数量",
  group: "分组", list: "列表", page: "页面", section: "区域", field: "字段", item: "项目",
  details: "详情", description: "描述", summary: "摘要", overview: "概览", stats: "统计",
  results: "结果", options: "选项", actions: "操作", permissions: "权限", members: "成员",
  workspaces: "工作区", keys: "密钥", credits: "积分", billing: "账单", invoices: "发票",
  notifications: "通知", preferences: "偏好", security: "安全", privacy: "隐私",
  language: "语言", appearance: "外观", profile: "资料", account: "账户",
};

// 无实义、翻译时直接省略的词
const OR_DROP = new Set(["the", "a", "an"]);