// OpenRouter 界面术语词典（全站）
// 键：页面叶子元素 trimmed textContent 的精确文本；值：中文翻译
// 只收录界面/术语，不收录模型名与长描述，避免误译
const OR_DICT = {
  // 主导航 / 通用
  "Models": "模型",
  "Benchmarks": "基准测试",
  "Chat": "对话",
  "Rankings": "排行榜",
  "Apps": "应用",
  "Docs": "文档",
  "Search": "搜索",
  "Sign Up": "注册",
  "Sign in": "登录",
  "Log in": "登录",
  "Log out": "退出登录",
  "Compare": "对比",
  "Discover Models": "发现模型",
  "Search models...": "搜索模型...",
  "List view": "列表视图",
  "Table view": "表格视图",
  "Table settings": "表格设置",
  "All": "全部",
  "Model Name": "模型名称",
  "Weekly Tokens": "周用量",
  "Input": "输入",
  "Output": "输出",
  "Context": "上下文",
  "Latency": "延迟",
  "Throughput": "吞吐量",
  "Released": "发布时间",
  "Pricing": "定价",
  "Enterprise": "企业版",
  "Labs": "实验室",
  "Discover": "发现",
  "Settings": "设置",
  "Account": "账户",
  "Keys": "密钥",
  "Credits": "积分",
  "Billing": "账单",
  "Usage": "用量",
  "Activity": "活动",
  "Profile": "个人资料",
  "Preferences": "偏好设置",
  "Notifications": "通知",
  "Dark mode": "深色模式",
  "Light mode": "浅色模式",
  "Language": "语言",
  "Help": "帮助",
  "Feedback": "反馈",
  "Cancel": "取消",
  "Save": "保存",
  "Saving": "保存中…",
  "Submit": "提交",
  "Delete": "删除",
  "Confirm": "确认",
  "Close": "关闭",
  "Copy": "复制",
  "Copied": "已复制",
  "View": "查看",
  "Open": "打开",
  "Back": "返回",
  "Next": "下一步",
  "Previous": "上一步",
  "Done": "完成",
  "Loading": "加载中…",
  "Loading...": "加载中…",
  "Error": "错误",
  "Warning": "警告",
  "Success": "成功",
  "Refresh": "刷新",
  "Reset": "重置",
  "Retry": "重试",
  "Learn more": "了解更多",
  "Read more": "阅读更多",
  "Show more": "展开更多",
  "Show less": "收起",
  "See more": "查看更多",
  "View all": "查看全部",
  "See all": "查看全部",
  "New": "新增",
  "NEW": "新增",
  "Popular": "热门",
  "Featured": "精选",
  "Trending": "热门趋势",
  "Recommended": "推荐",
  "Free": "免费",
  "Beta": "测试版",
  "Preview": "预览",
  "Deprecated": "已弃用",
  "Inactive": "已停用",
  "Active": "启用",
  "Enabled": "已启用",
  "Disabled": "已禁用",
  "Optional": "可选",
  "Required": "必填",
  "Default": "默认",
  "Custom": "自定义",
  "Advanced": "高级",
  "Basic": "基础",
  "Quickstart": "快速开始",
  "Getting Started": "开始使用",
  "Introduction": "简介",
  "Overview": "概览",
  "Guide": "指南",
  "Reference": "参考",
  "Examples": "示例",
  "FAQ": "常见问题",
  "Changelog": "更新日志",
  "Status": "状态",
  "Documentation": "文档",
  "API Reference": "API 参考",
  "Developer Platform": "开发者平台",
  "Community": "社区",
  "Support": "支持",
  "Contact": "联系我们",
  "About": "关于",
  "Blog": "博客",
  "Careers": "招聘",
  "Hiring": "招聘中",
  "Privacy": "隐私政策",
  "Terms": "条款",
  "Terms of Service": "服务条款",
  "Data": "数据",
  "Security": "安全",
  "Product": "产品",
  "Company": "公司",
  "Developer": "开发者",
  "Connect": "社区",
  // 筛选器（模型页）
  "Input Modalities": "输入模态",
  "Text": "文本",
  "Image": "图像",
  "File": "文件",
  "Audio": "音频",
  "Video": "视频",
  "Embeddings": "嵌入",
  "Rerank": "重排序",
  "Speech": "语音",
  "Transcription": "转录",
  "Discounted": "折扣模型",
  "Context length": "上下文长度",
  "Prompt pricing": "输入价格",
  "Series": "系列",
  "Categories": "分类",
  "Supported Parameters": "支持的参数",
  "Distillable": "可蒸馏",
  "Zero Data Retention": "零数据保留",
  "In-Region Routing": "区域内路由",
  "Information": "信息",
  "Output pricing": "输出价格",
  "Model age": "模型发布时间",
  "Tool Calling": "工具调用",
  "Inactive Models": "停用模型",
  "Providers": "提供商",
  "Model Authors": "模型作者",
  // 模型卡片
  "by": "作者",
  // 页面（chat）
  "New chat": "新建对话",
  "Send": "发送",
  "Stop": "停止",
  "Clear chat": "清空对话",
  "Delete chat": "删除对话",
  "Rename": "重命名",
  "Regenerate": "重新生成",
  "Copy code": "复制代码",
  "System prompt": "系统提示词",
  "Max tokens": "最大 Tokens",
  "Temperature": "温度",
  "Top P": "Top P",
  "Stop sequences": "停止序列",
  "Stream": "流式输出",
  "Markdown": "Markdown",
  "Share": "分享",
  "Export": "导出",
  "Import": "导入",
  "Untitled": "未命名",
  "Today": "今天",
  "Yesterday": "昨天",
  "Previous 7 days": "近 7 天",
  "Previous 30 days": "近 30 天",
  // 页面（benchmarks/rankings）
  "Overall": "综合",
  "Rank": "排名",
  "Votes": "投票数",
  "Arena": "竞技场",
  "Model": "模型",
  "Price": "价格",
  "Score": "分数",
  "Accuracy": "准确率",
  "Speed": "速度",
  "Quality": "质量",
  "Average": "平均",
  "Median": "中位数",
  "Total": "总计",
  // 页面（apps）
  "Add app": "添加应用",
  "Install": "安装",
  "Installed": "已安装",
  "Website": "网站",
  "GitHub": "GitHub",
  "Twitter": "Twitter",
  "Open source": "开源",
  // 页脚补充
  "Works With OR": "Works With OR",
  "Discord": "Discord",
  "LinkedIn": "LinkedIn",
  "YouTube": "YouTube",
  // ==== 2026-08 全站采集扩充（17 页 harvest） ====
  "Home": "首页",
  "List": "列表",
  "Chats": "对话",
  "Sign In": "登录",
  "Sign up": "注册",
  "Signup": "注册",
  "Sign Up For Free": "免费注册",
  "Get Started": "开始使用",
  "Get Started For Free": "免费开始",
  "Get API Key": "获取 API 密钥",
  "Get your API key": "获取您的 API 密钥",
  "Select": "选择",
  "Select a model": "选择模型",
  "Add Model": "添加模型",
  "No matching rooms": "无匹配对话",
  "Import Character": "导入角色",
  "Click to upload": "点击上传",
  "drag and drop": "拖放文件",
  "Insufficient credits": "积分不足",
  "Continue with free models": "使用免费模型继续",
  "Verify your email": "验证您的邮箱",
  "Dismiss": "忽略",
  "(opens in new tab)": "(在新标签页中打开)",
  "Skip to content": "跳到内容",
  "Skip to main content": "跳到主要内容",
  "Not available in this workspace": "当前工作区不可用",
  "Benchmark": "基准测试",
  "N/A": "不适用",
  "No": "否",
  "Yes": "是",
  "new": "新增",
  "Avg": "平均",
  "Absolute": "绝对值",
  "Percentage": "百分比",
  "Others": "其他",
  "English": "英语",
  "Provider": "提供商",
  "Retention": "保留",
  "Trains": "训练",
  "Headquarters": "总部",
  "Uptime": "可用性",
  "uptime": "可用性",
  "prices": "价格",
  "Buy credits": "购买积分",
  "Buy Credits": "购买积分",
  "Learn more →": "了解更多",
  "View more": "查看更多",
  "View more →": "查看更多",
  "Explore all models →": "浏览全部模型",
  "Enterprise features →": "企业版功能",
  "Try chat now →": "立即试用对话",
  "Read the full article →": "阅读全文",
  "View all announcements →": "查看全部公告",
  "View stats →": "查看统计",
  "View all": "查看全部",
  "View all benchmarks": "查看全部基准测试",
  "View all text models": "查看全部文本模型",
  "View all posts": "查看全部文章",
  "Browse all": "浏览全部",
  "Browse apps": "浏览应用",
  "Monthly Tokens": "月用量",
  "Global Users": "全球用户",
  "Text, Images, Videos, and Audio": "文本、图像、视频和音频",
  "Featured Models": "精选模型",
  "Custom Data Policies": "自定义数据策略",
  "Higher Availability": "更高可用性",
  "Price and Performance": "价格与性能",
  "Model routing visualization": "模型路由可视化",
  "Data policy visualization": "数据策略可视化",
  "500+ active models on 80+ providers": "80+ 提供商上的 500+ 个活跃模型",
  "Recent Blog Posts": "最新博客文章",
  "The Unified Interface For Every Model": "所有模型的统一接口",
  "Fully OpenAI compatible": "完全兼容 OpenAI",
  "Weekly Trend": "周趋势",
  "The easiest way to go from idea to app": "从创意到应用的最简单方式",
  "An autonomous agent that grows with you": "一个会随你成长的自主代理",
  "Flagship models": "旗舰模型",
  "Best roleplay models": "最佳角色扮演模型",
  "Best coding models": "最佳编程模型",
  "Reasoning models": "推理模型",
  "AI Model Rankings": "AI 模型排行榜",
  "LLM Leaderboard": "LLM 排行榜",
  "All models": "全部模型",
  "This Week": "本周",
  "Top Models": "热门模型",
  "Top Apps": "热门应用",
  "Top models by task": "按任务划分的热门模型",
  "Share of spend": "支出占比",
  "Cost per session": "每次会话成本",
  "Market Share": "市场份额",
  "Languages": "语言",
  "Programming": "编程",
  "Context Length": "上下文长度",
  "Tool Calls": "工具调用",
  "Tool usage across models on OpenRouter": "OpenRouter 上各模型的工具使用情况",
  "Images": "图像",
  "Total images processed on OpenRouter": "OpenRouter 处理的图像总数",
  "opting into": "选择加入",
  "opting into usage tracking": "选择加入使用统计",
  "Fastest growing this week": "本周增长最快",
  "Global Ranking": "全球排行榜",
  "model rankings": "模型排行榜",
  "full model list": "完整模型列表",
  "last run": "上次运行",
  "Fetching benchmark data via the API": "通过 API 获取基准数据",
  "task evaluations": "任务评估",
  "Family tokens": "家族用量",
  "Always-latest aliases": "始终最新的别名",
  "Fastest models": "最快模型",
  "Free models": "免费模型",
  "App & Agent Rankings": "应用与代理排行榜",
  "CLI Agents": "命令行代理",
  "Personal Agents": "个人代理",
  "IDE Extensions": "IDE 扩展",
  "Programming App": "编程应用",
  "Roleplay": "角色扮演",
  "General Chat": "通用对话",
  "Most Popular": "最受欢迎",
  "Top Coding Agents": "热门编程代理",
  "Top Productivity": "热门效率应用",
  "Top Creative": "热门创意应用",
  "Top Entertainment": "热门娱乐应用",
  "Creative Writing": "创意写作",
  "Video Generation": "视频生成",
  "Game": "游戏",
  "Build and play AI RPGs": "构建并畅玩 AI RPG",
  "Mira is a Telegram-native AI assistant.": "Mira 是一个 Telegram 原生 AI 助手。",
  "AI Video & Podcast Editor": "AI 视频与播客编辑器",
  "All-in-one creator store": "一站式创作者商店",
  "The AI tool for Roblox games.": "用于 Roblox 游戏的 AI 工具。",
  "Pay-as-you-go": "按量付费",
  "Platform Fees": "平台费用",
  "25+ free models": "25+ 个免费模型",
  "4 free providers": "4 个免费提供商",
  "Chat and API Access": "对话与 API 访问",
  "Activity Logs & Export": "活动日志与导出",
  "Budgets & Spend Controls": "预算与支出控制",
  "Prompt Caching": "提示词缓存",
  "Management API key": "管理 API 密钥",
  "Admin Controls": "管理员控制",
  "Data Policy-Based Routing": "基于数据策略的路由",
  "Model & provider policies": "模型与提供商策略",
  "Managed Policy Enforcement": "托管策略执行",
  "Contractual SLAs": "合同 SLA",
  "Payment options": "支付方式",
  "BYOK Limits": "BYOK 限制",
  "Rate limits": "速率限制",
  "Token Pricing": "Token 定价",
  "Free models only": "仅免费模型",
  "Community Support": "社区支持",
  "500+ models": "500+ 模型",
  "80+ providers": "80+ 提供商",
  "Contact Sales": "联系销售",
  "Talk To Sales": "联系销售",
  "Fee discounts available": "可享费率折扣",
  "Credit card, crypto & more": "信用卡、加密货币等",
  "Invoicing options": "发票选项",
  "High global limits": "高全球限额",
  "Optional dedicated limits": "可选专用限额",
  "No minimum spend. Prices based on models": "无最低消费，价格取决于模型",
  "Email Support": "邮件支持",
  "Support SLA with Shared Slack Channel": "含共享 Slack 频道的支持 SLA",
  "Frequently Asked Questions": "常见问题",
  "Billing and Pricing": "账单与定价",
  "Usage and Rate Limits": "用量与速率限制",
  "Routing and Latency": "路由与延迟",
  "Privacy and Security": "隐私与安全",
  "Models and Features": "模型与功能",
  "Reliability and Uptime": "可靠性与可用性",
  "Ready To Get Started?": "准备好开始了吗？",
  "Zero retention": "零保留",
  "Zero Retention": "零保留",
  "Retains prompts": "保留提示词",
  "30 day retention": "30 天保留",
  "55 day retention": "55 天保留",
  "Limited retention": "有限保留",
  "Training": "训练",
  "Trains on prompts": "使用提示词训练",
  "Does not train": "不训练",
  "Policies": "政策",
  "Has terms of service": "有服务条款",
  "Has privacy policy": "有隐私政策",
  "Access": "访问",
  "Supports BYOK": "支持 BYOK",
  "Moderation required": "需要审核",
  "Terms of service": "服务条款",
  "Privacy policy": "隐私政策",
  "Daily tokens": "日用量",
  "Monthly tokens": "月用量",
  "United States": "美国",
  "China": "中国",
  "Singapore": "新加坡",
  "Israel": "以色列",
  "AI Model Comparison": "AI 模型对比",
  "Most affordable": "最实惠",
  "Best for code": "最适合编程",
  "Designed for multi-step problem solving.": "专为多步问题求解而设计。",
  "Playground": "演示环境",
  "Sign in to try this model": "登录后试用此模型",
  "Get Code": "获取代码",
  "Quick Start": "快速开始",
  "Learn more in our docs": "在我们的文档中了解更多",
  "All locations": "所有地区",
  "Other benchmark results include:": "其他基准测试结果包括：",
  "Latency / throughput": "延迟 / 吞吐量",
  "Code Categories": "代码分类",
  "Data Visualization": "数据可视化",
  "Game Development": "游戏开发",
  "UI Component": "UI 组件",
  "Copy page": "复制页面",
  "Search...": "搜索...",
  "Batch": "批量",
  "Using the OpenRouter API": "使用 OpenRouter API",
  "Using the Client SDKs": "使用客户端 SDK",
  "Using the Agent SDK": "使用 Agent SDK",
  "Using the OpenAI SDK": "使用 OpenAI SDK",
  "Using third-party SDKs": "使用第三方 SDK",
  "Building with an AI assistant": "使用 AI 助手构建",
  "Client SDKs": "客户端 SDK",
  "Agent SDK": "Agent SDK",
  "Documentation Index": "文档索引",
  "Ask Assistant": "询问助手",
  "Navigation": "导航",
  "Principles": "原则",
  "Multimodal": "多模态",
  "Authentication": "身份验证",
  "Report Feedback": "报告反馈",
  "Models & Routing": "模型与路由",
  "Model Fallbacks": "模型回退",
  "Provider Selection": "提供商选择",
  "Private Models": "私有模型",
  "Model Variants": "模型变体",
  "Routers": "路由器",
  "Features": "功能",
  "Workspaces": "工作区",
  "Workspace Budgets": "工作区预算",
  "Switching Workspaces": "切换工作区",
  "Single Sign-On (SSO)": "单点登录 (SSO)",
  "SCIM Group Mappings": "SCIM 组映射",
  "Presets": "预设",
  "Custom Classifiers": "自定义分类器",
  "Response Caching": "响应缓存",
  "Server Tools": "服务端工具",
  "Plugins": "插件",
  "Structured Outputs": "结构化输出",
  "Message Transforms": "消息转换",
  "Zero Completion Insurance": "零补全保险",
  "App Attribution": "应用归因",
  "Guardrails": "护栏",
  "Service Tiers": "服务层级",
  "Sovereign AI": "主权 AI",
  "Router Metadata": "路由元数据",
  "Input & Output Logging": "输入与输出日志",
  "Provider looking to list models?": "提供商想在平台上架模型？",
  "Managing 5+ provider relationships": "管理 5+ 个提供商关系",
  "Building custom retry logic": "构建自定义重试逻辑",
  "Automatic failover between providers": "提供商之间自动故障转移",
  "Capacity and rate limits": "容量与速率限制",
  "Zero switching cost between models": "模型之间零切换成本",
  "Data retention and privacy concerns": "数据保留与隐私问题",
  "Manage compliance with each provider": "管理每个提供商的合规性",
  "From Proof-of-Concept to Production": "从概念验证到生产",
  "High Rate Limits": "高速率限制",
  "Automatic Failover": "自动故障转移",
  "Bring Your Own Capacity": "自带容量",
  "Unified Billing": "统一账单",
  "Compliance & Privacy": "合规与隐私",
  "Zero-Logging Default": "默认零日志",
  "Unified Reporting": "统一报告",
  "Organization Support with SSO": "组织级 SSO 支持",
  "Spend Management": "支出管理",
  "Enterprise-Grade AI Infrastructure": "企业级 AI 基础设施",
  "Traces": "追踪",
  "Observability broadcast visualization": "可观测性广播可视化",
  "LLM Observability": "LLM 可观测性",
  "Credit Limits": "积分限额",
  "Monthly Limit": "每月限额",
  "This Month": "本月",
  "Cost Management": "成本管理",
  "No logging": "无日志",
  "No training": "不训练",
  "Auto-delete": "自动删除",
  "Simple Setup & Billing": "简单设置与计费",
  "Payment Options": "支付方式",
  "Credit Card": "信用卡",
  "Instant setup with major credit cards": "使用主流信用卡即刻开通",
  "Invoiced Billing": "发票账单",
  "Buy credits in bulk for discounted fees": "批量购买积分享受折扣费率",
  "Credit Lines": "授信额度",
  "Transparent Pricing": "透明定价",
  "Configurable payment and top-up settings": "可配置的支付与充值设置",
  "No long-term contracts required": "无需长期合同",
  "International VAT compliance": "国际增值税合规",
  "Invoicing & detailed usage reporting": "发票与详细用量报告",
  "Enterprise Agreements": "企业协议",
  "Enterprise Support": "企业支持",
  "Priority Support Channels": "优先支持渠道",
  "Dedicated Engineering Contact": "专属工程联系人",
  "Data Protection & Privacy Agreements": "数据保护与隐私协议",
  "We can provide ours, or review yours.": "我们可以提供我们的协议，或审阅您的协议。",
  "SLAs": "SLA",
  "Technical Resources": "技术资源",
  "Enterprise Quickstart": "企业快速开始",
  "API Documentation": "API 文档",
  "Provider Routing Guide": "提供商路由指南",
  "Integration Examples": "集成示例",
  "Experiments": "实验",
  "Model Fusion": "模型融合",
  "Cost Simulator": "成本模拟器",
  "About OpenRouter": "关于 OpenRouter",
  "Backed by Leading Investors": "获得顶级投资者支持",
  "Announcements": "公告",
  "Tutorials": "教程",
  "Insights": "洞见",
  "Pinned": "置顶",
  "Recent Product Announcements": "近期产品公告",
  "Works with OpenRouter": "与 OpenRouter 兼容",
  "Submit a PR": "提交 PR",
  "See our OAuth docs": "查看我们的 OAuth 文档",
  "Featured Partnerships": "精选合作伙伴",
  "Talk to us": "联系我们",
  "productivity": "效率",
  "coding": "编程",
  "chat": "对话",
  "research": "研究",
  "creative": "创意",
  "Build autonomous AI agents effortlessly.": "轻松构建自主 AI 代理。",
  "The world fastest open code cli agent": "全球最快的开源代码 CLI 代理",
  "The open-source app builder.": "开源应用构建器。",
  "Semantic coding agent in the terminal": "终端中的语义编码代理",
  "Email address": "邮箱地址",
  "Password": "密码",
  "Don't have an account?": "没有账户？",
  "Don’t have an account?": "没有账户？",
  "Feature": "功能",
  "50 reqs/day": "50 次请求/天",
  // ==== 2026-08 文档/设置相关采集扩充（docs faq/limits/workspaces/budgets） ====
  "Getting started": "开始使用",
  "Pricing and fees": "定价与费用",
  "Models and providers": "模型与提供商",
  "API technical specifications": "API 技术规范",
  "Privacy and data logging": "隐私与数据日志",
  "Credit and billing systems": "积分与账单系统",
  "Account management": "账户管理",
  "On this page": "本页内容",
  "Activity tab": "活动标签页",
  "pricing page": "定价页面",
  "models browser": "模型浏览器",
  "rate limits documentation": "速率限制文档",
  "privacy settings": "隐私设置",
  "provider routing": "提供商路由",
  "Management API keys": "管理 API 密钥",
  "Management Keys": "管理密钥",
  "management API": "管理 API",
  "management API keys": "管理 API 密钥",
  "API documentation": "API 文档",
  "OpenAI SDK docs": "OpenAI SDK 文档",
  "API Guides": "API 指南",
  "Limits": "限额",
  "Credit limits": "积分限额",
  "Credit Limits and Rate Limits": "积分限额与速率限制",
  "Limit type": "限额类型",
  "What it governs": "作用范围",
  "Error on exceeding": "超限错误",
  "Where to check": "查看位置",
  "Checking your limits": "检查您的限额",
  "Handling 402 errors": "处理 402 错误",
  "Handling 429 errors": "处理 429 错误",
  "Mid-stream rate limits": "流式传输中的速率限制",
  "fallback models": "回退模型",
  "fallback routing": "回退路由",
  "Account balance": "账户余额",
  "Per-key credit limits": "每密钥积分限额",
  "Add credits": "添加积分",
  "Free usage limits": "免费用量限额",
  "Credits purchased (all time)": "累计购买积分",
  "Requests per minute": "每分钟请求数",
  "Requests per day": "每天请求数",
  "Less than 10": "少于 10",
  "At least 10": "至少 10",
  "DDoS protection": "DDoS 防护",
  "Rate limit exceeded": "超出速率限制",
  "The upstream provider": "上游提供商",
  "Retry with exponential backoff.": "使用指数退避重试。",
  "On free variants": "在免费变体上",
  "Errors and Debugging": "错误与调试",
  "Versioning": "版本管理",
  "API Versioning": "API 版本管理",
  "API Changelog": "API 更新日志",
  "Analytics": "分析",
  "Classifications": "分类",
  "Datasets": "数据集",
  "Endpoints": "端点",
  "Generations": "生成结果",
  "API Keys": "API 密钥",
  "Observability": "可观测性",
  "Organization": "组织",
  "Responses": "响应",
  "ZDR": "零数据保留",
  "Broadcast": "广播",
  "Best Practices": "最佳实践",
  "Latency and Performance": "延迟与性能",
  "Uptime Optimization": "可用性优化",
  "Reasoning Tokens": "推理 Tokens",
  "For Providers": "面向提供商",
  "Frameworks and Integrations Overview": "框架与集成概览",
  "Data Collection": "数据收集",
  "Provider Logging": "提供商日志",
  "Creating a New Workspace": "创建工作区",
  "What’s Scoped to Each Workspace": "每个工作区的范围",
  "What's Scoped to Each Workspace": "每个工作区的范围",
  "Account Level Settings": "账户级设置",
  "Organization Permissions": "组织权限",
  "Default workspace": "默认工作区",
  "home dashboard": "主页仪表盘",
  "Create Workspace": "创建工作区",
  "Members": "成员",
  "Budgets": "预算",
  "Logs": "日志",
  "Credits & Billing": "积分与账单",
  "Org admins": "组织管理员",
  "Org members": "组织成员",
  "workspace switcher": "工作区切换器",
  "sidebar workspace switcher": "侧边栏工作区切换器",
  "Assistant": "助手",
  "Routing": "路由",
  "Organization Administrators": "组织管理员",
  "Organization Administrator": "组织管理员",
  "Include BYOK spend": "包含 BYOK 支出",
  "Including BYOK Spend": "包含 BYOK 支出",
  "How It Works": "工作原理",
  "Ordering Rule": "排序规则",
  "Setting Budgets in the Dashboard": "在仪表盘中设置预算",
  "Setting Budgets via the API": "通过 API 设置预算",
  "List Budgets": "列出预算",
  "Create or Update a Budget": "创建或更新预算",
  "Delete a Budget": "删除预算",
  "Spend Tracking": "支出跟踪",
  "Budgets During Workspace Creation": "创建工作区时的预算",
  "Interval": "周期",
  "Resets": "重置时间",
  "Use case": "适用场景",
  "Every day at midnight UTC": "每天 UTC 午夜重置",
  "Every Monday at midnight UTC": "每周一 UTC 午夜重置",
  "Smooth out weekly burst usage": "平滑每周突发用量",
  "First of each month at midnight UTC": "每月 1 日 UTC 午夜重置",
  "Enforce a fixed monthly allocation": "强制执行固定月度分配",
  "Hard cap on total workspace spend": "工作区总支出上限",
  "Add budget": "添加预算",
  "Repeat for additional intervals": "为其他周期重复设置",
  "PDFs": "PDF 文件",
  "Privacy Policy": "隐私政策",
  "Daily": "每日",
  "Weekly": "每周",
  "Monthly": "每月",
  "Lifetime": "长期",
  "daily": "每日",
  "weekly": "每周",
  "monthly": "每月",
  "lifetime": "长期",
  "Common questions about OpenRouter": "关于 OpenRouter 的常见问题",
  "Why should I use OpenRouter?": "为什么使用 OpenRouter？",
  "Learn more in our Quickstart guide": "在快速开始指南中了解更多",
  "How do I get started with OpenRouter?": "如何开始使用 OpenRouter？",
  "How do I get support?": "如何获得支持？",
  "What are the fees for using OpenRouter?": "使用 OpenRouter 的费用是多少？",
  "Crypto payments are charged a fee of 5%.": "加密货币支付收取 5% 的费用。",
  "Learn more about BYOK": "了解更多 BYOK 信息",
  "What LLM models does OpenRouter support?": "OpenRouter 支持哪些 LLM 模型？",
  "How frequently are new models added?": "新模型多久添加一次？",
  "What are model variants?": "什么是模型变体？",
  "Learn more about API authentication": "了解更多 API 身份验证信息",
  "How are rate limits calculated?": "速率限制如何计算？",
  "What API endpoints are available?": "有哪些 API 端点？",
  "What are the supported formats?": "支持哪些格式？",
  "How does streaming work?": "流式输出如何工作？",
  "Learn more about streaming": "了解更多流式输出信息",
  "What SDK support is available?": "支持哪些 SDK？",
  "What data is logged during API use?": "API 使用期间会记录哪些数据？",
  "Learn more about data collection": "了解更多数据收集信息",
  "What data is logged during Chatroom use?": "聊天室使用期间会记录哪些数据？",
  "What third-party sharing occurs?": "会发生哪些第三方共享？",
  "What purchase options exist?": "有哪些购买方式？",
  "Do credits expire?": "积分会过期吗？",
  "What's the refund policy?": "退款政策是什么？",
  "How to monitor credit usage?": "如何监控积分使用？",
  "What free tier options exist?": "有哪些免费层级选项？",
  "Is my Chat/Fusion usage in a workspace?": "我的对话/Fusion 用量在工作区中吗？",
  // ==== 2026-08 设置页采集扩充（用户粘贴：workspace/keys/credits/security/preferences/notifications） ====
  "Default Workspace": "默认工作区",
  "Classifiers": "分类器",
  "Introducing Workspaces!": "工作区介绍！",
  "This Week's Usage": "本周用量",
  "This Week’s Usage": "本周用量",
  "View Activity": "查看活动",
  "No spend this week": "本周无支出",
  "No requests this week": "本周无请求",
  "No tokens this week": "本周无 Tokens",
  "Web Search": "联网搜索",
  "Search providers...": "搜索提供商...",
  "Available": "可用",
  "Not configured": "未配置",
  "Key Priority and Fallback": "密钥优先级与回退",
  "Always use this key": "始终使用此密钥",
  "Auto Router": "自动路由",
  "Cost Tier": "成本档位",
  "Low (Default)": "低（默认）",
  "Restrict to Allowed Model List": "限制为允许的模型列表",
  "Prevent overrides": "禁止覆盖",
  "Default Provider Sort": "默认提供商排序",
  "Default (balanced)": "默认（均衡）",
  "Default Model": "默认模型",
  "No default": "无默认",
  "Less": "减少",
  "More": "更多",
  "Active keys": "有效密钥",
  "Disabled / expired": "已禁用 / 已过期",
  "Last created": "最近创建",
  "Name": "名称",
  "Key": "密钥",
  "Workspace": "工作区",
  "Created": "创建时间",
  "Usage summary": "用量摘要",
  "Last 7 Days": "最近 7 天",
  "Spend": "支出",
  "Requests": "请求数",
  "View full activity": "查看完整活动",
  "Daily by model": "按模型每日",
  "this month": "本月",
  "Top models": "热门模型",
  "by spend": "按支出",
  "No usage in this period": "该时段无用量",
  "Longest streak": "最长连续",
  "Avg / day": "日均",
  "Avg / week": "周均",
  "Past 1 Month": "过去 1 个月",
  "Trends": "趋势",
  "Explore": "探索",
  "Explore ›": "探索 ›",
  "Total spend": "总支出",
  "Token volume": "Token 量",
  "Cache hit rate": "缓存命中率",
  "Blended $/1M": "综合 $/1M",
  "Top API Keys": "热门 API 密钥",
  "Usage by model": "按模型用量",
  "Usage type": "用量类型",
  "Request volume by model": "按模型请求量",
  "Token breakdown": "Token 构成",
  "Reasoning": "推理",
  "Completion": "补全",
  "Prompt": "提示词",
  "Prompt token caching": "提示词缓存",
  "Uncached": "未缓存",
  "Cached": "已缓存",
  "Past 24 Hours": "过去 24 小时",
  "Upstream Requests": "上游请求",
  "Sessions": "会话",
  "Videos": "视频",
  "Batches": "批次",
  "Date": "日期",
  "App": "应用",
  "Cost": "成本",
  "Usage Type": "用量类型",
  "Routing Overhead": "路由开销",
  "Time to First Token": "首个 Token 时间",
  "Finish Reason": "结束原因",
  "API Key": "API 密钥",
  "No transactions found": "未找到交易记录",
  "Total available": "可用总额",
  "Pay-as-you-go balance": "按量付费余额",
  "Use crypto": "使用加密货币",
  "View Usage": "查看用量",
  "Redeem Promo Code": "兑换优惠码",
  "Auto Top-Up": "自动充值",
  "Enable": "启用",
  "Recent Transactions": "最近交易",
  "History": "历史记录",
  "Amount": "金额",
  "Actions": "操作",
  "Receipt": "收据",
  "Get invoice": "获取发票",
  "New Key": "新建密钥",
  "No management keys yet": "还没有管理密钥",
  "Data Policies": "数据策略",
  "Non-frontier": "非前沿模型",
  "Data Training": "数据训练",
  "Allow paid endpoints that train on request data": "允许对请求数据训练的付费端点",
  "Allow free endpoints that train on request data": "允许对请求数据训练的免费端点",
  "Allow free endpoints that publish prompts": "允许发布提示词的免费端点",
  "Allow 1% data discount in workspaces": "允许工作区使用 1% 数据折扣",
  "Allowed Providers": "允许的提供商",
  "Ignored Providers": "忽略的提供商",
  "Add": "添加",
  "Eligibility Preview": "可用性预览",
  "Show All": "显示全部",
  "Prompt Injection Allowlist": "提示词注入白名单",
  "Add pattern": "添加模式",
  "User": "用户",
  "Manage": "管理",
  "Create": "创建",
  "Create and manage your organization.": "创建并管理您的组织。",
  "Account Type": "账户类型",
  "Your current account tier.": "您当前的账户层级。",
  "Self Serve": "自助服务",
  "Date Format": "日期格式",
  "Default Preset": "默认预设",
  "None": "无",
  "Enable analytics cookies": "启用分析 Cookie",
  "Low Balance Alerts": "余额不足提醒",
  "Chat Completion Notifications": "对话补全通知",
  "Attestations": "声明",
  "18+ age confirmation": "18 岁以上年龄确认",
  // 月份（日期选择器）
  "January": "一月", "February": "二月", "March": "三月", "April": "四月",
  "May": "五月", "June": "六月", "July": "七月", "August": "八月",
  "September": "九月", "October": "十月", "November": "十一月", "December": "十二月",
  "Jan": "1月", "Feb": "2月", "Mar": "3月", "Apr": "4月",
  "Jun": "6月", "Jul": "7月", "Aug": "8月", "Sep": "9月",
  "Oct": "10月", "Nov": "11月", "Dec": "12月",
  // ==== 2026-08 用户菜单补充 ====
  "Personal": "个人版",
  "personal": "个人版",
  // ==== 2026-08 常见设置短语（优先于常用词兜底） ====
  "First Name": "名",
  "Last Name": "姓",
  "Display Name": "显示名称",
  "Full Name": "全名",
  "Time Zone": "时区",
  "Email Address": "邮箱",
  "Phone Number": "电话号码",
  "Current Password": "当前密码",
  "New Password": "新密码",
  "Confirm Password": "确认密码",
  "Save Changes": "保存更改",
  "Change Password": "修改密码",
  "Reset Password": "重置密码",
  "Account Settings": "账户设置",
  "Profile Picture": "头像",
  "Billing Address": "账单地址",
  "Payment Method": "支付方式",
  "Two-Factor Authentication": "两步验证",
  "2FA": "两步验证",
  "Sign Out": "退出登录",
  "Sign out": "退出登录",
  "Dark Theme": "深色主题",
  "Light Theme": "浅色主题",
  "Notification Settings": "通知设置",
  "Privacy Settings": "隐私设置",
  "Security Settings": "安全设置",
  "General Settings": "通用设置",
  "Manage Account": "管理账户",
  "Delete Account": "删除账户",
  "Change Email": "修改邮箱",
  "Add Payment Method": "添加支付方式",
  "Upgrade Plan": "升级套餐",
  "Downgrade Plan": "降级套餐",
  "Current Plan": "当前套餐",
  "Plan": "套餐",
  "Billing Cycle": "计费周期",
  "Renewal Date": "续费日期",
  "Cancel Subscription": "取消订阅",
  "Trial Ended": "试用已结束",
  "Expires": "到期时间",
};